version: "3.9"

services:
  kds-db:
    image: postgres:14
    container_name: kds-db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=kds
    network_mode: host

  kds-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kds-app_kds-app:latest
    container_name: kds-app
    environment:
      - SQL_URL=jdbc:postgresql://localhost:5432/kds
      - SQL_USERNAME=root
      - SQL_PASSWORD=123456
    ports:
      - "8000:8000"
    depends_on:
      - kds-db
    network_mode: host