databaseChangeLog:
  - changeSet:
      id: products.NEW_FIELD_PACKAGE.30.03.25.12.55
      author: rakitin
      changes:
        - addColumn:
            tableName: ingredient
            columns:
              - column:
                  name: fc_price
                  type: FLOAT8
        - addColumn:
            tableName: prepack
            columns:
              - column:
                  name: fc_price
                  type: FLOAT8
        - addColumn:
            tableName: menu_item
            columns:
              - column:
                  name: fc_price
                  type: FLOAT8