server:
  port: 8000
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
  liquibase:
    enabled: true
    change-log: classpath:/liquibase/db.changelog-master.yaml