create table recipe_menu_item
(
    final_amount        double precision                                                  not null,
    init_amount         double precision                                                  not null,
    losses_amount       double precision                                                  not null,
    losses_percentage   double precision                                                  not null,
    id                  bigint default nextval('menu_item_recipe_id_generator'::regclass) not null
        primary key,
    menu_item_id        bigint                                                            not null
        constraint fk_recipe_menu_item_menu_item_id_flow_id
            references menu_item,
    source_id           bigint                                                            not null,
    station_id          bigint                                                            not null,
    source_type         varchar(255)                                                      not null,
    measurement_unit_id bigint
        constraint recipe_menu_item__measurement_id_fk
            references measurement,
    priority            bigint default 100                                                not null,
    constraint recipe_menu_item__mi_si_unique_pk
        unique (menu_item_id, source_id, station_id)
);

alter table recipe_menu_item
    owner to root;

INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (20, 20, 0, 0, 173, 6, 5, 4, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (60, 60, 0, 0, 158, 4, 12, 1, 'INGREDIENT', 1, 30);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (100, 100, 0, 0, 102, 27, 9, 3, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (60, 60, 0, 0, 29, 1, 12, 1, 'INGREDIENT', 1, 30);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (30, 30, 0, 0, 72, 22, 12, 1, 'INGREDIENT', 1, 30);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (30, 30, 0, 0, 187, 10, 3, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (90, 90, 0, 0, 54, 18, 14, 1, 'PREPACK', 1, 10);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (60, 60, 0, 0, 13, 13, 12, 1, 'INGREDIENT', 1, 30);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (30, 30, 0, 0, 89, 25, 12, 1, 'INGREDIENT', 1, 30);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (60, 60, 0, 0, 27, 20, 12, 1, 'INGREDIENT', 1, 30);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (3, 3, 0, 0, 126, 37, 19, 3, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (20, 20, 0, 0, 164, 32, 18, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (20, 20, 0, 0, 137, 31, 15, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (60, 60, 0, 0, 35, 2, 12, 1, 'INGREDIENT', 1, 30);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (60, 60, 0, 0, 8, 12, 12, 1, 'INGREDIENT', 1, 30);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (120, 120, 0, 0, 56, 20, 14, 1, 'PREPACK', 1, 10);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (10, 10, 0, 0, 10, 12, 45, 1, 'INGREDIENT', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (10, 10, 0, 0, 103, 27, 24, 4, 'INGREDIENT', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (0.5, 0.5, 0, 0, 143, 20, 46, 1, 'INGREDIENT', 2, 20);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (20, 20, 0, 0, 125, 34, 14, 1, 'PREPACK', 1, 10);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (10, 10, 0, 0, 26, 19, 24, 4, 'INGREDIENT', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (60, 60, 0, 0, 105, 28, 3, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (20, 20, 0, 0, 188, 10, 20, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (30, 30, 0, 0, 189, 10, 15, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (20, 20, 0, 0, 175, 7, 20, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (20, 20, 0, 0, 100, 27, 20, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (50, 50, 0, 0, 101, 27, 59, 1, 'INGREDIENT', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (30, 30, 0, 0, 31, 1, 20, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (20, 20, 0, 0, 170, 6, 20, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (80, 80, 0, 0, 172, 6, 15, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (10, 10, 0, 0, 71, 21, 24, 4, 'INGREDIENT', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (10, 10, 0, 0, 171, 6, 21, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (10, 10, 0, 0, 98, 26, 24, 4, 'INGREDIENT', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (60, 60, 0, 0, 161, 4, 17, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (10, 10, 0, 0, 30, 20, 45, 1, 'INGREDIENT', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (0.5, 0.5, 0, 0, 152, 29, 46, 1, 'INGREDIENT', 2, 20);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (50, 50, 0, 0, 86, 24, 60, 1, 'INGREDIENT', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (50, 50, 0, 0, 177, 7, 18, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (20, 20, 0, 0, 179, 8, 20, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (60, 60, 0, 0, 185, 9, 16, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (80, 80, 0, 0, 156, 3, 15, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (20, 20, 0, 0, 119, 31, 14, 1, 'PREPACK', 1, 10);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (120, 120, 0, 0, 57, 21, 14, 1, 'PREPACK', 1, 10);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (120, 120, 0, 0, 59, 23, 14, 1, 'PREPACK', 1, 10);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (120, 120, 0, 0, 37, 1, 14, 1, 'PREPACK', 1, 10);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (120, 120, 0, 0, 63, 27, 14, 1, 'PREPACK', 1, 10);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (120, 120, 0, 0, 61, 25, 14, 1, 'PREPACK', 1, 10);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (120, 120, 0, 0, 55, 19, 14, 1, 'PREPACK', 1, 10);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (90, 90, 0, 0, 51, 15, 14, 1, 'PREPACK', 1, 10);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (90, 90, 0, 0, 52, 16, 14, 1, 'PREPACK', 1, 10);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (90, 90, 0, 0, 53, 17, 14, 1, 'PREPACK', 1, 10);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (30, 30, 0, 0, 28, 20, 20, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (1, 1, 0, 0, 145, 22, 46, 1, 'INGREDIENT', 2, 20);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (1, 1, 0, 0, 142, 19, 46, 1, 'INGREDIENT', 2, 20);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (30, 30, 0, 0, 14, 13, 20, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (30, 30, 0, 0, 24, 19, 20, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (1, 1, 0, 0, 140, 17, 46, 1, 'INGREDIENT', 2, 20);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (1, 1, 0, 0, 138, 15, 46, 1, 'INGREDIENT', 2, 20);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (10, 10, 0, 0, 6, 11, 2, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (0.5, 0.5, 0, 0, 132, 9, 46, 1, 'INGREDIENT', 2, 20);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (120, 120, 0, 0, 104, 28, 14, 1, 'PREPACK', 1, 10);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (30, 30, 0, 0, 12, 12, 1, 3, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (120, 120, 0, 0, 39, 3, 14, 1, 'PREPACK', 1, 10);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (20, 20, 0, 0, 123, 32, 14, 1, 'PREPACK', 1, 10);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (120, 120, 0, 0, 33, 2, 14, 1, 'PREPACK', 1, 10);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (120, 120, 0, 0, 47, 11, 14, 1, 'PREPACK', 1, 10);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (120, 120, 0, 0, 45, 9, 14, 1, 'PREPACK', 1, 10);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (120, 120, 0, 0, 41, 5, 14, 1, 'PREPACK', 1, 10);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (120, 120, 0, 0, 43, 7, 14, 1, 'PREPACK', 1, 10);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (120, 120, 0, 0, 48, 12, 14, 1, 'PREPACK', 1, 10);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (120, 120, 0, 0, 49, 13, 14, 1, 'PREPACK', 1, 10);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (120, 120, 0, 0, 65, 30, 14, 1, 'PREPACK', 1, 10);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (120, 120, 0, 0, 64, 29, 14, 1, 'PREPACK', 1, 10);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (120, 120, 0, 0, 60, 24, 14, 1, 'PREPACK', 1, 10);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (120, 120, 0, 0, 62, 26, 14, 1, 'PREPACK', 1, 10);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (60, 60, 0, 0, 21, 17, 18, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (10, 10, 0, 0, 180, 8, 21, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (20, 20, 0, 0, 165, 5, 20, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (80, 80, 0, 0, 32, 1, 15, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (10, 10, 0, 0, 82, 23, 24, 4, 'INGREDIENT', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (30, 30, 0, 0, 183, 9, 3, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (1, 1, 0, 0, 130, 7, 46, 1, 'INGREDIENT', 2, 20);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (1, 1, 0, 0, 146, 23, 46, 1, 'INGREDIENT', 2, 20);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (0.5, 0.5, 0, 0, 144, 21, 46, 1, 'INGREDIENT', 2, 20);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (80, 80, 0, 0, 181, 8, 16, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (1, 1, 0, 0, 150, 27, 46, 1, 'INGREDIENT', 2, 20);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (1, 1, 0, 0, 148, 25, 46, 1, 'INGREDIENT', 2, 20);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (0.5, 0.5, 0, 0, 153, 30, 46, 1, 'INGREDIENT', 2, 20);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (30, 30, 0, 0, 174, 7, 12, 1, 'INGREDIENT', 1, 30);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (30, 30, 0, 0, 154, 3, 12, 1, 'INGREDIENT', 1, 30);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (50, 50, 0, 0, 91, 25, 17, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (20, 20, 0, 0, 2, 5, 12, 3, 'INGREDIENT', 1, 30);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (80, 80, 0, 0, 75, 22, 10, 3, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (90, 90, 0, 0, 50, 14, 14, 1, 'PREPACK', 1, 10);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (20, 20, 0, 0, 186, 9, 33, 1, 'INGREDIENT', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (10, 10, 0, 0, 93, 25, 1, 4, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (30, 30, 0, 0, 77, 20, 1, 3, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (1, 1, 0, 0, 124, 1, 46, 1, 'INGREDIENT', 2, 20);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (20, 20, 0, 0, 73, 22, 20, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (0.5, 0.5, 0, 0, 129, 6, 46, 1, 'INGREDIENT', 2, 20);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (60, 60, 0, 0, 74, 22, 16, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (80, 80, 0, 0, 92, 25, 10, 3, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (0.5, 0.5, 0, 0, 128, 5, 46, 1, 'INGREDIENT', 2, 20);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (20, 20, 0, 0, 90, 25, 20, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (10, 10, 0, 0, 88, 24, 1, 4, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (30, 30, 0, 0, 70, 21, 1, 3, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (30, 30, 0, 0, 168, 5, 31, 3, 'INGREDIENT', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (20, 20, 0, 0, 79, 23, 20, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (10, 10, 0, 0, 84, 24, 23, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (10, 10, 0, 0, 83, 24, 20, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (50, 50, 0, 0, 80, 23, 15, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (80, 80, 0, 0, 97, 26, 10, 3, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (20, 20, 0, 0, 3, 11, 20, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (60, 60, 0, 0, 5, 11, 18, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (30, 30, 0, 0, 4, 11, 15, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (80, 80, 0, 0, 81, 23, 10, 3, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (60, 60, 0, 0, 19, 15, 17, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (0.5, 0.5, 0, 0, 134, 11, 46, 1, 'INGREDIENT', 2, 20);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (0.5, 0.5, 0, 0, 135, 12, 46, 1, 'INGREDIENT', 2, 20);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (0.5, 0.5, 0, 0, 136, 13, 46, 1, 'INGREDIENT', 2, 20);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (0.25, 0.25, 0, 0, 201, 35, 46, 1, 'INGREDIENT', 2, 20);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (0.25, 0.25, 0, 0, 204, 36, 46, 1, 'INGREDIENT', 2, 20);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (5, 5, 0, 0, 200, 35, 24, 1, 'INGREDIENT', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (60, 60, 0, 0, 196, 38, 12, 3, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (20, 20, 0, 0, 193, 34, 17, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (60, 60, 0, 0, 194, 37, 10, 3, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (20, 20, 0, 0, 203, 36, 16, 1, 'PREPACK', 1, 1);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (20, 20, 0, 0, 198, 35, 14, 1, 'PREPACK', 1, 10);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (10, 10, 0, 0, 118, 30, 2, 4, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (10, 10, 0, 0, 116, 30, 21, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (80, 80, 0, 0, 117, 30, 15, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (30, 30, 0, 0, 106, 28, 20, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (10, 10, 0, 0, 108, 28, 2, 4, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (10, 10, 0, 0, 110, 29, 20, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (60, 60, 0, 0, 111, 29, 15, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (60, 60, 0, 0, 23, 19, 3, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (50, 50, 0, 0, 96, 26, 59, 1, 'INGREDIENT', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (10, 10, 0, 0, 85, 24, 22, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (80, 80, 0, 0, 167, 5, 15, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (10, 10, 0, 0, 166, 5, 21, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (30, 30, 0, 0, 78, 23, 12, 1, 'INGREDIENT', 1, 30);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (20, 20, 0, 0, 115, 30, 20, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (10, 10, 0, 0, 162, 4, 24, 1, 'INGREDIENT', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (60, 60, 0, 0, 20, 16, 16, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (60, 60, 0, 0, 22, 18, 20, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (60, 60, 0, 0, 16, 13, 18, 3, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (80, 80, 0, 0, 113, 29, 11, 3, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (30, 30, 0, 0, 94, 26, 12, 1, 'INGREDIENT', 1, 30);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (60, 60, 0, 0, 18, 14, 15, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (30, 30, 0, 0, 112, 29, 33, 1, 'INGREDIENT', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (30, 30, 0, 0, 67, 21, 20, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (60, 60, 0, 0, 69, 21, 17, 3, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (10, 10, 0, 0, 68, 21, 21, 1, 'INGREDIENT', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (20, 20, 0, 0, 95, 26, 20, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (80, 80, 0, 0, 87, 24, 10, 3, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (10, 10, 0, 0, 176, 7, 21, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (60, 60, 0, 0, 163, 5, 12, 1, 'INGREDIENT', 1, 30);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (100, 100, 0, 0, 25, 19, 13, 3, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (20, 20, 0, 0, 184, 9, 20, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (60, 60, 0, 0, 114, 30, 12, 1, 'INGREDIENT', 1, 30);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (10, 10, 0, 0, 76, 22, 24, 4, 'INGREDIENT', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (10, 10, 0, 0, 160, 4, 21, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (20, 20, 0, 0, 36, 2, 20, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (30, 30, 0, 0, 9, 12, 20, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (10, 10, 0, 0, 15, 13, 45, 1, 'INGREDIENT', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (80, 80, 0, 0, 107, 28, 12, 3, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (10, 10, 0, 0, 1, 2, 21, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (20, 20, 0, 0, 190, 10, 33, 1, 'INGREDIENT', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (60, 60, 0, 0, 66, 21, 12, 1, 'INGREDIENT', 1, 30);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (10, 10, 0, 0, 182, 8, 2, 4, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (60, 60, 0, 0, 169, 6, 12, 1, 'INGREDIENT', 1, 30);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (30, 30, 0, 0, 109, 29, 12, 1, 'INGREDIENT', 1, 30);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (30, 30, 0, 0, 99, 27, 12, 1, 'INGREDIENT', 1, 30);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (60, 60, 0, 0, 7, 11, 12, 1, 'INGREDIENT', 1, 30);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (0.5, 0.5, 0, 0, 127, 4, 46, 1, 'INGREDIENT', 2, 20);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (1, 1, 0, 0, 149, 26, 46, 1, 'INGREDIENT', 2, 20);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (1, 1, 0, 0, 17, 14, 46, 1, 'INGREDIENT', 2, 20);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (1, 1, 0, 0, 139, 16, 46, 1, 'INGREDIENT', 2, 20);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (1, 1, 0, 0, 141, 18, 46, 1, 'INGREDIENT', 2, 20);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (0.5, 0.5, 0, 0, 133, 10, 46, 1, 'INGREDIENT', 2, 20);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (0.5, 0.5, 0, 0, 131, 8, 46, 1, 'INGREDIENT', 2, 20);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (40, 40, 0, 0, 157, 3, 16, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (20, 20, 0, 0, 155, 3, 20, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (20, 20, 0, 0, 159, 4, 20, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (60, 60, 0, 0, 38, 20, 15, 3, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (60, 60, 0, 0, 11, 12, 15, 3, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (60, 60, 0, 0, 178, 8, 12, 1, 'INGREDIENT', 1, 30);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (1, 1, 0, 0, 147, 24, 46, 1, 'INGREDIENT', 2, 20);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (0.5, 0.5, 0, 0, 34, 2, 46, 1, 'INGREDIENT', 2, 20);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (1, 1, 0, 0, 151, 28, 46, 1, 'INGREDIENT', 2, 20);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (20, 20, 0, 0, 199, 35, 17, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (3, 3, 0, 0, 195, 38, 19, 3, 'PREPACK', 2, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (200, 200, 0, 0, 197, 39, 61, 3, 'INGREDIENT', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (20, 20, 0, 0, 192, 33, 16, 1, 'PREPACK', 1, 100);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (5, 5, 0, 0, 205, 36, 2, 1, 'PREPACK', 1, 1);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (120, 120, 0, 0, 58, 22, 14, 1, 'PREPACK', 1, 10);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (120, 120, 0, 0, 46, 10, 14, 1, 'PREPACK', 1, 10);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (120, 120, 0, 0, 44, 8, 14, 1, 'PREPACK', 1, 10);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (120, 120, 0, 0, 40, 4, 14, 1, 'PREPACK', 1, 10);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (120, 120, 0, 0, 42, 6, 14, 1, 'PREPACK', 1, 10);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (20, 20, 0, 0, 191, 33, 14, 1, 'PREPACK', 1, 10);
INSERT INTO public.recipe_menu_item (final_amount, init_amount, losses_amount, losses_percentage, id, menu_item_id, source_id, station_id, source_type, measurement_unit_id, priority) VALUES (20, 20, 0, 0, 202, 36, 14, 1, 'PREPACK', 1, 10);
