create table recipe_menu_item_aud
(
    final_amount        double precision,
    init_amount         double precision,
    losses_amount       double precision,
    losses_percentage   double precision,
    rev                 integer not null
        constraint fk_recipe_menu_item_aud_rev_revinfo_rev
            references revinfo,
    revtype             smallint,
    id                  bigint  not null,
    menu_item_id        bigint,
    source_id           bigint,
    station_id          bigint,
    source_type         varchar(255),
    priority            bigint,
    measurement_unit_id bigint,
    primary key (rev, id)
);

alter table recipe_menu_item_aud
    owner to root;

INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (30, 30, 0, 0, 1, 1, 31, 1, 20, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (20, 20, 0, 0, 2, 1, 36, 2, 20, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (10, 10, 0, 0, 7, 0, 1, 2, 21, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (30, 30, 0, 0, 52, 1, 154, 3, 12, 1, 'INGREDIENT', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (20, 20, 0, 0, 53, 1, 155, 3, 20, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (20, 20, 0, 0, 54, 1, 159, 4, 20, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (20, 20, 0, 0, 55, 1, 165, 5, 20, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (30, 30, 0, 0, 56, 1, 168, 5, 31, 3, 'INGREDIENT', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (20, 20, 0, 0, 57, 0, 2, 5, 12, 3, 'INGREDIENT', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (20, 20, 0, 0, 58, 1, 170, 6, 20, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (20, 20, 0, 0, 59, 1, 175, 7, 20, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (50, 50, 0, 0, 60, 1, 177, 7, 18, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (20, 20, 0, 0, 61, 1, 179, 8, 20, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (30, 30, 0, 0, 62, 1, 183, 9, 3, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (20, 20, 0, 0, 63, 1, 184, 9, 20, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (20, 20, 0, 0, 64, 1, 188, 10, 20, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (20, 20, 0, 0, 65, 0, 3, 11, 20, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (30, 30, 0, 0, 66, 0, 4, 11, 15, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (60, 60, 0, 0, 67, 0, 5, 11, 18, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (10, 10, 0, 0, 68, 0, 6, 11, 2, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (60, 60, 0, 0, 69, 0, 7, 11, 12, 1, 'INGREDIENT', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (0.5, 0.5, 0, 0, 70, 1, 134, 11, 46, 1, 'INGREDIENT', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (0.5, 0.5, 0, 0, 71, 1, 135, 12, 46, 1, 'INGREDIENT', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (60, 60, 0, 0, 72, 0, 8, 12, 12, 1, 'INGREDIENT', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (30, 30, 0, 0, 73, 0, 9, 12, 20, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (10, 10, 0, 0, 74, 0, 10, 12, 45, 1, 'INGREDIENT', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (60, 60, 0, 0, 75, 0, 11, 12, 15, 3, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (30, 30, 0, 0, 76, 0, 12, 12, 1, 3, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (0.5, 0.5, 0, 0, 77, 1, 136, 13, 46, 1, 'INGREDIENT', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (60, 60, 0, 0, 78, 0, 13, 13, 12, 1, 'INGREDIENT', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (30, 30, 0, 0, 79, 0, 14, 13, 20, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (10, 10, 0, 0, 80, 0, 15, 13, 45, 1, 'INGREDIENT', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (60, 60, 0, 0, 81, 0, 16, 13, 18, 3, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (100, 100, 0, 0, 82, 1, 50, 14, 14, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (1, 1, 0, 0, 83, 0, 17, 14, 46, 1, 'INGREDIENT', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (60, 60, 0, 0, 84, 0, 18, 14, 15, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (100, 100, 0, 0, 85, 1, 51, 15, 14, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (60, 60, 0, 0, 86, 0, 19, 15, 17, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (100, 100, 0, 0, 87, 1, 52, 16, 14, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (60, 60, 0, 0, 88, 0, 20, 16, 16, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (100, 100, 0, 0, 89, 1, 53, 17, 14, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (60, 60, 0, 0, 90, 0, 21, 17, 18, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (100, 100, 0, 0, 91, 1, 54, 18, 14, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (60, 60, 0, 0, 92, 0, 22, 18, 20, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (60, 60, 0, 0, 93, 0, 23, 19, 3, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (30, 30, 0, 0, 94, 0, 24, 19, 20, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (100, 100, 0, 0, 95, 0, 25, 19, 13, 3, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (10, 10, 0, 0, 96, 0, 26, 19, 24, 1, 'INGREDIENT', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (60, 60, 0, 0, 97, 0, 27, 20, 12, 1, 'INGREDIENT', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (30, 30, 0, 0, 98, 0, 28, 20, 20, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (10, 10, 0, 0, 99, 0, 30, 20, 45, 1, 'INGREDIENT', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (60, 60, 0, 0, 100, 0, 38, 20, 15, 3, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (0.5, 0.5, 0, 0, 101, 1, 143, 20, 46, 1, 'INGREDIENT', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (0.5, 0.5, 0, 0, 102, 1, 144, 21, 46, 1, 'INGREDIENT', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (60, 60, 0, 0, 103, 0, 66, 21, 12, 1, 'INGREDIENT', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (30, 30, 0, 0, 104, 0, 67, 21, 20, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (10, 10, 0, 0, 105, 0, 68, 21, 21, 1, 'INGREDIENT', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (60, 60, 0, 0, 106, 0, 69, 21, 17, 3, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (30, 30, 0, 0, 107, 0, 70, 21, 1, 3, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (10, 10, 0, 0, 108, 0, 71, 21, 24, 4, 'INGREDIENT', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (30, 30, 0, 0, 109, 0, 72, 22, 12, 1, 'INGREDIENT', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (20, 20, 0, 0, 110, 0, 73, 22, 20, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (60, 60, 0, 0, 111, 0, 74, 22, 16, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (80, 80, 0, 0, 112, 0, 75, 22, 10, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (10, 10, 0, 0, 113, 0, 76, 22, 24, 4, 'INGREDIENT', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (80, 80, 0, 0, 114, 1, 75, 22, 10, 3, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (10, 10, 0, 0, 115, 1, 26, 19, 24, 4, 'INGREDIENT', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (30, 30, 0, 0, 116, 0, 77, 20, 1, 3, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (30, 30, 0, 0, 117, 0, 78, 23, 12, 1, 'INGREDIENT', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (20, 20, 0, 0, 118, 0, 79, 23, 20, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (50, 50, 0, 0, 119, 0, 80, 23, 15, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (80, 80, 0, 0, 120, 0, 81, 23, 10, 3, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (10, 10, 0, 0, 121, 0, 82, 23, 24, 4, 'INGREDIENT', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (10, 10, 0, 0, 122, 0, 83, 24, 20, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (10, 10, 0, 0, 131, 0, 84, 24, 23, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (10, 10, 0, 0, 132, 0, 85, 24, 22, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (50, 50, 0, 0, 133, 0, 86, 24, 60, 1, 'INGREDIENT', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (80, 80, 0, 0, 134, 0, 87, 24, 10, 3, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (10, 10, 0, 0, 136, 0, 88, 24, 1, 4, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (30, 30, 0, 0, 138, 0, 89, 25, 12, 1, 'INGREDIENT', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (20, 20, 0, 0, 140, 0, 90, 25, 20, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (50, 50, 0, 0, 141, 0, 91, 25, 17, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (80, 80, 0, 0, 142, 0, 92, 25, 10, 3, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (10, 10, 0, 0, 143, 0, 93, 25, 1, 4, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (30, 30, 0, 0, 144, 0, 94, 26, 12, 1, 'INGREDIENT', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (20, 20, 0, 0, 149, 0, 95, 26, 20, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (50, 50, 0, 0, 150, 0, 96, 26, 59, 1, 'INGREDIENT', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (80, 80, 0, 0, 151, 0, 97, 26, 10, 3, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (10, 10, 0, 0, 152, 0, 98, 26, 24, 4, 'INGREDIENT', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (30, 30, 0, 0, 157, 0, 99, 27, 12, 1, 'INGREDIENT', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (20, 20, 0, 0, 158, 0, 100, 27, 20, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (50, 50, 0, 0, 159, 0, 101, 27, 59, 1, 'INGREDIENT', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (100, 100, 0, 0, 160, 0, 102, 27, 9, 3, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (10, 10, 0, 0, 161, 0, 103, 27, 24, 4, 'INGREDIENT', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (120, 120, 0, 0, 162, 0, 104, 28, 14, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (60, 60, 0, 0, 163, 0, 105, 28, 3, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (30, 30, 0, 0, 164, 0, 106, 28, 20, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (80, 80, 0, 0, 165, 0, 107, 28, 12, 3, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (10, 10, 0, 0, 166, 0, 108, 28, 2, 4, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (0.5, 0.5, 0, 0, 167, 1, 152, 29, 46, 1, 'INGREDIENT', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (30, 30, 0, 0, 168, 0, 109, 29, 12, 1, 'INGREDIENT', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (10, 10, 0, 0, 169, 0, 110, 29, 20, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (60, 60, 0, 0, 170, 0, 111, 29, 15, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (30, 30, 0, 0, 171, 0, 112, 29, 33, 1, 'INGREDIENT', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (80, 80, 0, 0, 172, 0, 113, 29, 11, 3, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (0.5, 0.5, 0, 0, 173, 1, 153, 30, 46, 1, 'INGREDIENT', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (60, 60, 0, 0, 174, 0, 114, 30, 12, 1, 'INGREDIENT', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (20, 20, 0, 0, 175, 0, 115, 30, 20, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (10, 10, 0, 0, 176, 0, 116, 30, 21, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (80, 80, 0, 0, 177, 0, 117, 30, 15, 1, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (10, 10, 0, 0, 180, 0, 118, 30, 2, 4, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (20, 20, 0, 0, 181, 1, 173, 6, 5, 4, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (10, 10, 0, 0, 182, 1, 182, 8, 2, 4, 'PREPACK', null, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (20, 20, 0, 0, 202, 0, 119, 31, 14, 1, 'PREPACK', 1, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (20, 20, 0, 0, 203, 0, 123, 32, 14, 1, 'PREPACK', 1, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (20, 20, 0, 0, 204, 0, 125, 34, 14, 1, 'PREPACK', 1, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (3, 3, 0, 0, 205, 0, 126, 37, 19, 3, 'PREPACK', 1, null);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (20, 20, 0, 0, 252, 0, 137, 31, 15, 1, 'PREPACK', 1, 1);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (20, 20, 0, 0, 253, 0, 164, 32, 18, 1, 'PREPACK', 1, 1);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (20, 20, 0, 0, 254, 0, 191, 33, 14, 1, 'PREPACK', 1, 1);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (20, 20, 0, 0, 255, 0, 192, 33, 16, 1, 'PREPACK', 1, 1);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (20, 20, 0, 0, 256, 0, 193, 34, 17, 1, 'PREPACK', 1, 1);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (60, 60, 0, 0, 257, 0, 194, 37, 10, 1, 'PREPACK', 1, 1);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (3, 3, 0, 0, 258, 0, 195, 38, 19, 1, 'PREPACK', 1, 2);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (60, 60, 0, 0, 259, 0, 196, 38, 12, 1, 'PREPACK', 1, 1);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (200, 200, 0, 0, 260, 0, 197, 39, 61, 3, 'INGREDIENT', 1, 1);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (60, 60, 0, 0, 261, 1, 194, 37, 10, 3, 'PREPACK', 1, 1);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (60, 60, 0, 0, 262, 1, 196, 38, 12, 3, 'PREPACK', 1, 1);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (3, 3, 0, 0, 263, 1, 195, 38, 19, 3, 'PREPACK', 1, 2);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (20, 20, 0, 0, 264, 0, 198, 35, 14, 1, 'PREPACK', 1, 1);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (20, 20, 0, 0, 265, 0, 199, 35, 17, 1, 'PREPACK', 1, 1);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (5, 5, 0, 0, 266, 0, 200, 35, 24, 1, 'INGREDIENT', 1, 1);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (0.25, 0.25, 0, 0, 267, 0, 201, 35, 46, 1, 'INGREDIENT', 1, 2);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (20, 20, 0, 0, 268, 0, 202, 36, 14, 1, 'PREPACK', 1, 1);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (20, 20, 0, 0, 269, 0, 203, 36, 16, 1, 'PREPACK', 1, 1);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (0.25, 0.25, 0, 0, 270, 0, 204, 36, 46, 1, 'INGREDIENT', 1, 2);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (5, 5, 0, 0, 271, 0, 205, 36, 2, 1, 'PREPACK', 1, 1);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (40, 40, 0, 0, 496, 1, 157, 3, 16, 1, 'PREPACK', 100, 1);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (30, 30, 0, 0, 497, 1, 187, 10, 3, 1, 'PREPACK', 100, 1);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (90, 90, 0, 0, 501, 1, 50, 14, 14, 1, 'PREPACK', 10, 1);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (90, 90, 0, 0, 502, 1, 51, 15, 14, 1, 'PREPACK', 10, 1);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (90, 90, 0, 0, 503, 1, 52, 16, 14, 1, 'PREPACK', 10, 1);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (90, 90, 0, 0, 504, 1, 53, 17, 14, 1, 'PREPACK', 10, 1);
INSERT INTO public.recipe_menu_item_aud (final_amount, init_amount, losses_amount, losses_percentage, rev, revtype, id, menu_item_id, source_id, station_id, source_type, priority, measurement_unit_id) VALUES (90, 90, 0, 0, 505, 1, 54, 18, 14, 1, 'PREPACK', 10, 1);
